# Generated by Django 4.2.8 on 2025-05-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('role', models.CharField(choices=[('N', 'Nurse'), ('D', 'Doctor')], max_length=1)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lmp', models.DateField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pulse', models.PositiveIntegerField()),
                ('respiration', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=10)),
                ('o_sat', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('religion', models.CharField(max_length=55)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('admission_date', models.DateTimeField()),
                ('chief_complaint', models.TextField()),
                ('admitting_diagnosis', models.TextField()),
                ('past_illness', models.TextField()),
                ('previous_hospitalization', models.TextField()),
                ('surgeries', models.TextField()),
                ('injuries', models.TextField()),
                ('family_history', models.TextField()),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patiends_as_nurse', to='crud.user')),
                ('physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_as_physician', to='crud.user')),
            ],
            options={
                'db_table': 'tbl_patients',
            },
        ),
    ]
